[build]
    functions = "netlify_functions"

[functions]
    loadDictionaryHandler = { schedule = "*/5 * * * *" }  # Run every 5 minutes

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200