[build]
    functions = "netlify_functions"

[functions]
    included_files = [
        "netlify_functions/dictionary.dawg.json",
        "netlify_functions/leaves.json",
        "netlify_functions/dictionary.gaddag.json"
    ]
    node_bundler = "esbuild"
    external_node_modules = ["aws-sdk"]
    memory = 1024

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200